var _skills = [
        {
            genre: "sg_environment",
            skills: [
                { skill: "Botanist", points: 1, type: 1, name: "Botanist Lv1" },
                { skill: "Botanist", points: 2, type: 1, name: "Botanist Lv2" },
                { skill: "Botanist", points: 3, type: 1, name: "Botanist Lv3" },
                { skill: "Botanist", points: 4, type: 1, name: "Botanist Lv4" },
                { skill: "Carving Pro", points: 1, type: 1, name: "Carving Pro Lv1" },
                { skill: "Cliffhanger", points: 1, type: 1, name: "Cliffhanger Lv1" },
                { skill: "Detector", points: 1, type: 1, name: "Detector Lv1" },
                { skill: "Effluvia Expert", points: 1, type: 1, name: "Effluvia Expert Lv1" },
                { skill: "Entomologist", points: 1, type: 1, name: "Entomologist Lv1" },
                { skill: "Entomologist", points: 2, type: 1, name: "Entomologist Lv2" },
                { skill: "Entomologist", points: 3, type: 1, name: "Entomologist Lv3" },
                { skill: "Forager\u2019s Luck", points: 1, type: 1, name: "Forager\u2019s Luck Lv1" },
                { skill: "Geologist", points: 1, type: 1, name: "Geologist Lv1" },
                { skill: "Geologist", points: 2, type: 1, name: "Geologist Lv2" },
                { skill: "Geologist", points: 3, type: 1, name: "Geologist Lv3" },
                { skill: "Heat Guard", points: 1, type: 1, name: "Heat Guard Lv1" },
                { skill: "Honey Hunter", points: 1, type: 1, name: "Honey Hunter Lv1" },
                { skill: "Hunger Resistance", points: 1, type: 1, name: "Hunger Resistance Lv1" },
                { skill: "Hunger Resistance", points: 2, type: 1, name: "Hunger Resistance Lv2" },
                { skill: "Hunger Resistance", points: 3, type: 1, name: "Hunger Resistance Lv3" },
                { skill: "Intimidator", points: 1, type: 1, name: "Intimidator Lv1" },
                { skill: "Intimidator", points: 2, type: 1, name: "Intimidator Lv2" },
                { skill: "Intimidator", points: 3, type: 1, name: "Intimidator Lv3" },
                { skill: "Master Fisher", points: 1, type: 1, name: "Master Fisher Lv1" },
                { skill: "Master Gatherer", points: 1, type: 1, name: "Master Gatherer Lv1" },
                { skill: "Pro Transporter", points: 1, type: 1, name: "Pro Transporter Lv1" },
                { skill: "Scent Hound", points: 1, type: 1, name: "Scent Hound Lv1" },
                { skill: "Scholar", points: 1, type: 1, name: "Scholar Lv1" },
                { skill: "Scoutfly Range Up", points: 1, type: 1, name: "Scoutfly Range Up Lv1" },
                { skill: "Speed Crawler", points: 1, type: 1, name: "Speed Crawler Lv1" },
                { skill: "Survival Expert", points: 1, type: 1, name: "Survival Expert Lv1" },
                { skill: "Survival Expert", points: 2, type: 1, name: "Survival Expert Lv2" },
                { skill: "Survival Expert", points: 3, type: 1, name: "Survival Expert Lv3" },
            ]
        },
        {
            genre: "sg_items",
            skills: [
                { skill: "BBQ Master", points: 1, type: 1, name: "BBQ Master Lv1" },
                { skill: "Blindsider", points: 1, type: 1, name: "Blindsider Lv1" },
                { skill: "Bombardier", points: 1, type: 1, name: "Bombardier Lv1" },
                { skill: "Bombardier", points: 2, type: 1, name: "Bombardier Lv2" },
                { skill: "Bombardier", points: 3, type: 1, name: "Bombardier Lv3" },
                { skill: "Dungmaster", points: 1, type: 1, name: "Dungmaster Lv1" },
                { skill: "Free Meal", points: 1, type: 1, name: "Free Meal Lv1" },
                { skill: "Heavy Artillery", points: 1, type: 1, name: "Heavy Artillery Lv1" },
                { skill: "Heavy Artillery", points: 2, type: 1, name: "Heavy Artillery Lv2" },
                { skill: "Item Prolonger", points: 1, type: 1, name: "Item Prolonger Lv1" },
                { skill: "Item Prolonger", points: 2, type: 1, name: "Item Prolonger Lv2" },
                { skill: "Item Prolonger", points: 3, type: 1, name: "Item Prolonger Lv3" },
                { skill: "Mushroomancer", points: 1, type: 1, name: "Mushroomancer Lv1" },
                { skill: "Mushroomancer", points: 2, type: 1, name: "Mushroomancer Lv2" },
                { skill: "Mushroomancer", points: 3, type: 1, name: "Mushroomancer Lv3" },
                { skill: "Recovery Up", points: 1, type: 1, name: "Recovery Up Lv1" },
                { skill: "Recovery Up", points: 2, type: 1, name: "Recovery Up Lv2" },
                { skill: "Recovery Up", points: 3, type: 1, name: "Recovery Up Lv3" },
                { skill: "Slinger Capacity", points: 1, type: 1, name: "Slinger Capacity Lv1" },
                { skill: "Slinger Capacity", points: 2, type: 1, name: "Slinger Capacity Lv2" },
                { skill: "Slinger Capacity", points: 3, type: 1, name: "Slinger Capacity Lv3" },
                { skill: "Speed Eating", points: 1, type: 1, name: "Speed Eating Lv1" },
                { skill: "Speed Eating", points: 2, type: 1, name: "Speed Eating Lv2" },
                { skill: "Speed Eating", points: 3, type: 1, name: "Speed Eating Lv3" },
                { skill: "Tool Specialist", points: 1, type: 1, name: "Tool Specialist Lv1" },
                { skill: "Tool Specialist", points: 2, type: 1, name: "Tool Specialist Lv2" },
                { skill: "Tool Specialist", points: 3, type: 1, name: "Tool Specialist Lv3" },
                { skill: "Wide-Range", points: 1, type: 1, name: "Wide-Range Lv1" },
                { skill: "Wide-Range", points: 2, type: 1, name: "Wide-Range Lv2" },
                { skill: "Wide-Range", points: 3, type: 1, name: "Wide-Range Lv3" },
                { skill: "Wide-Range", points: 4, type: 1, name: "Wide-Range Lv4" },
                { skill: "Wide-Range", points: 5, type: 1, name: "Wide-Range Lv5" }
            ]
        },
        {
            genre: "sg_survival",
            skills: [
                { skill: "Aquatic/Polar Mobility", points: 1, type: 1, name: "Aquatic/Polar Mobility Lv1" },
                { skill: "Aquatic/Polar Mobility", points: 2, type: 1, name: "Aquatic/Polar Mobility Lv2" },
                { skill: "Aquatic/Polar Mobility", points: 3, type: 1, name: "Aquatic/Polar Mobility Lv3" },
                { skill: "Blight Resistance", points: 1, type: 1, name: "Blight Resistance Lv1" },
                { skill: "Blight Resistance", points: 2, type: 1, name: "Blight Resistance Lv2" },
                { skill: "Blight Resistance", points: 3, type: 1, name: "Blight Resistance Lv3" },
                { skill: "Bleeding Resistance", points: 1, type: 1, name: "Bleeding Resistance Lv1" },
                { skill: "Bleeding Resistance", points: 2, type: 1, name: "Bleeding Resistance Lv2" },
                { skill: "Bleeding Resistance", points: 3, type: 1, name: "Bleeding Resistance Lv3" },
                { skill: "Earplugs", points: 1, type: 1, name: "Earplugs Lv1" },
                { skill: "Earplugs", points: 2, type: 1, name: "Earplugs Lv2" },
                { skill: "Earplugs", points: 3, type: 1, name: "Earplugs Lv3" },
                { skill: "Earplugs", points: 4, type: 1, name: "Earplugs Lv4" },
                { skill: "Earplugs", points: 5, type: 1, name: "Earplugs Lv5" },
                { skill: "Effluvia Resistance", points: 1, type: 1, name: "Effluvia Resistance Lv1" },
                { skill: "Effluvia Resistance", points: 2, type: 1, name: "Effluvia Resistance Lv2" },
                { skill: "Effluvia Resistance", points: 3, type: 1, name: "Effluvia Resistance Lv3" },
                { skill: "Evade Extender", points: 1, type: 1, name: "Evade Extender Lv1" },
                { skill: "Evade Extender", points: 2, type: 1, name: "Evade Extender Lv2" },
                { skill: "Evade Extender", points: 3, type: 1, name: "Evade Extender Lv3" },
                { skill: "Evade Window", points: 1, type: 1, name: "Evade Window Lv1" },
                { skill: "Evade Window", points: 2, type: 1, name: "Evade Window Lv2" },
                { skill: "Evade Window", points: 3, type: 1, name: "Evade Window Lv3" },
                { skill: "Evade Window", points: 4, type: 1, name: "Evade Window Lv4" },
                { skill: "Evade Window", points: 5, type: 1, name: "Evade Window Lv5" },
                { skill: "Flinch Free", points: 1, type: 1, name: "Flinch Free Lv1" },
                { skill: "Flinch Free", points: 2, type: 1, name: "Flinch Free Lv2" },
                { skill: "Flinch Free", points: 3, type: 1, name: "Flinch Free Lv3" },
                { skill: "Iron Skin", points: 1, type: 1, name: "Iron Skin Lv1" },
                { skill: "Iron Skin", points: 2, type: 1, name: "Iron Skin Lv2" },
                { skill: "Iron Skin", points: 3, type: 1, name: "Iron Skin Lv3" },
                { skill: "Leap of Faith", points: 1, type: 1, name: "Leap of Faith Lv1" },
                { skill: "Muck Resistance", points: 1, type: 1, name: "Muck Resistance Lv1" },
                { skill: "Paralysis Resistance", points: 1, type: 1, name: "Paralysis Resistance Lv1" },
                { skill: "Paralysis Resistance", points: 2, type: 1, name: "Paralysis Resistance Lv2" },
                { skill: "Paralysis Resistance", points: 3, type: 1, name: "Paralysis Resistance Lv3" },
                { skill: "Poison Resistance", points: 1, type: 1, name: "Poison Resistance Lv1" },
                { skill: "Poison Resistance", points: 2, type: 1, name: "Poison Resistance Lv2" },
                { skill: "Poison Resistance", points: 3, type: 1, name: "Poison Resistance Lv3" },
                { skill: "Recovery Speed", points: 1, type: 1, name: "Recovery Speed Lv1" },
                { skill: "Recovery Speed", points: 2, type: 1, name: "Recovery Speed Lv2" },
                { skill: "Recovery Speed", points: 3, type: 1, name: "Recovery Speed Lv3" },
                { skill: "Resuscitate", points: 1, type: 1, name: "Resuscitate Lv1" },
                { skill: "Sleep Resistance", points: 1, type: 1, name: "Sleep Resistance Lv1" },
                { skill: "Sleep Resistance", points: 2, type: 1, name: "Sleep Resistance Lv2" },
                { skill: "Sleep Resistance", points: 3, type: 1, name: "Sleep Resistance Lv3" },
                { skill: "Stealth", points: 1, type: 1, name: "Stealth Lv1" },
                { skill: "Stealth", points: 2, type: 1, name: "Stealth Lv2" },
                { skill: "Stealth", points: 3, type: 1, name: "Stealth Lv3" },
                { skill: "Stun Resistance", points: 1, type: 1, name: "Stun Resistance Lv1" },
                { skill: "Stun Resistance", points: 2, type: 1, name: "Stun Resistance Lv2" },
                { skill: "Stun Resistance", points: 3, type: 1, name: "Stun Resistance Lv3" },
                { skill: "Tremor Resistance", points: 1, type: 1, name: "Tremor Resistance Lv1" },
                { skill: "Tremor Resistance", points: 2, type: 1, name: "Tremor Resistance Lv2" },
                { skill: "Tremor Resistance", points: 3, type: 1, name: "Tremor Resistance Lv3" },
                { skill: "Windproof", points: 1, type: 1, name: "Windproof Lv1" },
                { skill: "Windproof", points: 2, type: 1, name: "Windproof Lv2" },
                { skill: "Windproof", points: 3, type: 1, name: "Windproof Lv3" },
                { skill: "Windproof", points: 4, type: 1, name: "Windproof Lv4" },
                { skill: "Windproof", points: 5, type: 1, name: "Windproof Lv5" }
            ]
        },
        {
            genre: "sg_resistance",
            skills: [
                { skill: "Blast Resistance", points: 1, type: 1, name: "Blast Resistance Lv1" },
                { skill: "Blast Resistance", points: 2, type: 1, name: "Blast Resistance Lv2" },
                { skill: "Blast Resistance", points: 3, type: 1, name: "Blast Resistance Lv3" },
                { skill: "Defense Boost", points: 1, type: 1, name: "Defense Boost Lv1" },
                { skill: "Defense Boost", points: 2, type: 1, name: "Defense Boost Lv2" },
                { skill: "Defense Boost", points: 3, type: 1, name: "Defense Boost Lv3" },
                { skill: "Defense Boost", points: 4, type: 1, name: "Defense Boost Lv4" },
                { skill: "Defense Boost", points: 5, type: 1, name: "Defense Boost Lv5" },
                { skill: "Defense Boost", points: 6, type: 1, name: "Defense Boost Lv6" },
                { skill: "Defense Boost", points: 7, type: 1, name: "Defense Boost Lv7" },
                { skill: "Divine Blessing", points: 1, type: 1, name: "Divine Blessing Lv1" },
                { skill: "Divine Blessing", points: 2, type: 1, name: "Divine Blessing Lv2" },
                { skill: "Divine Blessing", points: 3, type: 1, name: "Divine Blessing Lv3" },
                { skill: "Dragon Resistance", points: 1, type: 1, name: "Dragon Resistance Lv1" },
                { skill: "Dragon Resistance", points: 2, type: 1, name: "Dragon Resistance Lv2" },
                { skill: "Dragon Resistance", points: 3, type: 1, name: "Dragon Resistance Lv3" },
                { skill: "Fire Resistance", points: 1, type: 1, name: "Fire Resistance Lv1" },
                { skill: "Fire Resistance", points: 2, type: 1, name: "Fire Resistance Lv2" },
                { skill: "Fire Resistance", points: 3, type: 1, name: "Fire Resistance Lv3" },
                { skill: "Guard", points: 1, type: 1, name: "Guard Lv1" },
                { skill: "Guard", points: 2, type: 1, name: "Guard Lv2" },
                { skill: "Guard", points: 3, type: 1, name: "Guard Lv3" },
                { skill: "Guard", points: 4, type: 1, name: "Guard Lv4" },
                { skill: "Guard", points: 5, type: 1, name: "Guard Lv5" },
                { skill: "Guard Up", points: 1, type: 1, name: "Guard Up Lv1" },
                { skill: "Health Boost", points: 1, type: 1, name: "Health Boost Lv1" },
                { skill: "Health Boost", points: 2, type: 1, name: "Health Boost Lv2" },
                { skill: "Health Boost", points: 3, type: 1, name: "Health Boost Lv3" },
                { skill: "Ice Resistance", points: 1, type: 1, name: "Ice Resistance Lv1" },
                { skill: "Ice Resistance", points: 2, type: 1, name: "Ice Resistance Lv2" },
                { skill: "Ice Resistance", points: 3, type: 1, name: "Ice Resistance Lv3" },
                { skill: "Thunder Resistance", points: 1, type: 1, name: "Thunder Resistance Lv1" },
                { skill: "Thunder Resistance", points: 2, type: 1, name: "Thunder Resistance Lv2" },
                { skill: "Thunder Resistance", points: 3, type: 1, name: "Thunder Resistance Lv3" },
                { skill: "Water Resistance", points: 1, type: 1, name: "Water Resistance Lv1" },
                { skill: "Water Resistance", points: 2, type: 1, name: "Water Resistance Lv2" },
                { skill: "Water Resistance", points: 3, type: 1, name: "Water Resistance Lv3" },
            ]
        },
        {
            genre: "sg_special",
            skills: [
                { skill: "Constitution", points: 1, type: 1, name: "Constitution Lv1" },
                { skill: "Constitution", points: 2, type: 1, name: "Constitution Lv2" },
                { skill: "Constitution", points: 3, type: 1, name: "Constitution Lv3" },
                { skill: "Constitution", points: 4, type: 1, name: "Constitution Lv4" },
                { skill: "Constitution", points: 5, type: 1, name: "Constitution Lv5" },
                { skill: "Focus", points: 1, type: 1, name: "Focus Lv1" },
                { skill: "Focus", points: 2, type: 1, name: "Focus Lv2" },
                { skill: "Focus", points: 3, type: 1, name: "Focus Lv3" },
                { skill: "Free Elem/Ammo Up", points: 1, type: 1, name: "Free Elem/Ammo Up Lv1" },
                { skill: "Free Elem/Ammo Up", points: 2, type: 1, name: "Free Elem/Ammo Up Lv2" },
                { skill: "Free Elem/Ammo Up", points: 3, type: 1, name: "Free Elem/Ammo Up Lv3" },
                { skill: "Jump Master", points: 1, type: 1, name: "Jump Master Lv1" },
                { skill: "Marathon Runner", points: 1, type: 1, name: "Marathon Runner Lv1" },
                { skill: "Marathon Runner", points: 2, type: 1, name: "Marathon Runner Lv2" },
                { skill: "Marathon Runner", points: 3, type: 1, name: "Marathon Runner Lv3" },
                { skill: "Master Mounter", points: 1, type: 1, name: "Master Mounter Lv1" },
                { skill: "Mind\u2019s Eye/Ballistics", points: 1, type: 1, name: "Mind\u2019s Eye/Ballistics Lv1" },
                { skill: "Palico Rally", points: 1, type: 1, name: "Palico Rally Lv1" },
                { skill: "Palico Rally", points: 2, type: 1, name: "Palico Rally Lv2" },
                { skill: "Palico Rally", points: 3, type: 1, name: "Palico Rally Lv3" },
                { skill: "Palico Rally", points: 4, type: 1, name: "Palico Rally Lv4" },
                { skill: "Palico Rally", points: 5, type: 1, name: "Palico Rally Lv5" },
                { skill: "Partbreaker", points: 1, type: 1, name: "Partbreaker Lv1" },
                { skill: "Partbreaker", points: 2, type: 1, name: "Partbreaker Lv2" },
                { skill: "Partbreaker", points: 3, type: 1, name: "Partbreaker Lv3" },
                { skill: "Stamina Surge", points: 1, type: 1, name: "Stamina Surge Lv1" },
                { skill: "Stamina Surge", points: 2, type: 1, name: "Stamina Surge Lv2" },
                { skill: "Stamina Surge", points: 3, type: 1, name: "Stamina Surge Lv3" },
                { skill: "Quick Sheath", points: 1, type: 1, name: "Quick Sheath Lv1" },
                { skill: "Quick Sheath", points: 2, type: 1, name: "Quick Sheath Lv2" },
                { skill: "Quick Sheath", points: 3, type: 1, name: "Quick Sheath Lv3" }
            ]
        },
        {
            genre: "sg_ele_status_attack",
            skills: [
                { skill: "Blast Attack", points: 1, type: 1, name: "Blast Attack Lv1" },
                { skill: "Blast Attack", points: 2, type: 1, name: "Blast Attack Lv2" },
                { skill: "Blast Attack", points: 3, type: 1, name: "Blast Attack Lv3" },
                { skill: "Dragon Attack", points: 1, type: 1, name: "Dragon Attack Lv1" },
                { skill: "Dragon Attack", points: 2, type: 1, name: "Dragon Attack Lv2" },
                { skill: "Dragon Attack", points: 3, type: 1, name: "Dragon Attack Lv3" },
                { skill: "Dragon Attack", points: 4, type: 1, name: "Dragon Attack Lv4" },
                { skill: "Dragon Attack", points: 5, type: 1, name: "Dragon Attack Lv5" },
                { skill: "Elderseal Boost", points: 1, type: 1, name: "Elderseal Boost Lv1" },
                { skill: "Fire Attack", points: 1, type: 1, name: "Fire Attack Lv1" },
                { skill: "Fire Attack", points: 2, type: 1, name: "Fire Attack Lv2" },
                { skill: "Fire Attack", points: 3, type: 1, name: "Fire Attack Lv3" },
                { skill: "Fire Attack", points: 4, type: 1, name: "Fire Attack Lv4" },
                { skill: "Fire Attack", points: 5, type: 1, name: "Fire Attack Lv5" },
                { skill: "Ice Attack", points: 1, type: 1, name: "Ice Attack Lv1" },
                { skill: "Ice Attack", points: 2, type: 1, name: "Ice Attack Lv2" },
                { skill: "Ice Attack", points: 3, type: 1, name: "Ice Attack Lv3" },
                { skill: "Ice Attack", points: 4, type: 1, name: "Ice Attack Lv4" },
                { skill: "Ice Attack", points: 5, type: 1, name: "Ice Attack Lv5" },
                { skill: "Paralysis Attack", points: 1, type: 1, name: "Paralysis Attack Lv1" },
                { skill: "Paralysis Attack", points: 2, type: 1, name: "Paralysis Attack Lv2" },
                { skill: "Paralysis Attack", points: 3, type: 1, name: "Paralysis Attack Lv3" },
                { skill: "Poison Attack", points: 1, type: 1, name: "Poison Attack Lv1" },
                { skill: "Poison Attack", points: 2, type: 1, name: "Poison Attack Lv2" },
                { skill: "Poison Attack", points: 3, type: 1, name: "Poison Attack Lv3" },
                { skill: "Sleep Attack", points: 1, type: 1, name: "Sleep Attack Lv1" },
                { skill: "Sleep Attack", points: 2, type: 1, name: "Sleep Attack Lv2" },
                { skill: "Sleep Attack", points: 3, type: 1, name: "Sleep Attack Lv3" },
                { skill: "Slugger", points: 1, type: 1, name: "Slugger Lv1" },
                { skill: "Slugger", points: 2, type: 1, name: "Slugger Lv2" },
                { skill: "Slugger", points: 3, type: 1, name: "Slugger Lv3" },
                { skill: "Stamina Thief", points: 1, type: 1, name: "Stamina Thief Lv1" },
                { skill: "Stamina Thief", points: 2, type: 1, name: "Stamina Thief Lv2" },
                { skill: "Stamina Thief", points: 3, type: 1, name: "Stamina Thief Lv3" },
                { skill: "Thunder Attack", points: 1, type: 1, name: "Thunder Attack Lv1" },
                { skill: "Thunder Attack", points: 2, type: 1, name: "Thunder Attack Lv2" },
                { skill: "Thunder Attack", points: 3, type: 1, name: "Thunder Attack Lv3" },
                { skill: "Thunder Attack", points: 4, type: 1, name: "Thunder Attack Lv4" },
                { skill: "Thunder Attack", points: 5, type: 1, name: "Thunder Attack Lv5" },
                { skill: "Water Attack", points: 1, type: 1, name: "Water Attack Lv1" },
                { skill: "Water Attack", points: 2, type: 1, name: "Water Attack Lv2" },
                { skill: "Water Attack", points: 3, type: 1, name: "Water Attack Lv3" },
                { skill: "Water Attack", points: 4, type: 1, name: "Water Attack Lv4" },
                { skill: "Water Attack", points: 5, type: 1, name: "Water Attack Lv5" }
            ]
        },
  {
            genre: "sg_melee",
            skills: [
                { skill: "Capacity Boost", points: 1, type: 1, name: "Capacity Boost Lv1" },
                { skill: "Handicraft", points: 1, type: 1, name: "Handicraft Lv1" },
                { skill: "Handicraft", points: 2, type: 1, name: "Handicraft Lv2" },
                { skill: "Handicraft", points: 3, type: 1, name: "Handicraft Lv3" },
                { skill: "Handicraft", points: 4, type: 1, name: "Handicraft Lv4" },
                { skill: "Handicraft", points: 5, type: 1, name: "Handicraft Lv5" },
                { skill: "Horn Maestro", points: 1, type: 1, name: "Horn Maestro Lv1" },
                { skill: "Power Prolonger", points: 1, type: 1, name: "Power Prolonger Lv1" },
                { skill: "Power Prolonger", points: 2, type: 1, name: "Power Prolonger Lv2" },
                { skill: "Power Prolonger", points: 3, type: 1, name: "Power Prolonger Lv3" },
                { skill: "Protective Polish", points: 1, type: 1, name: "Protective Polish Lv1" },
                { skill: "Speed Sharpening", points: 1, type: 1, name: "Speed Sharpening Lv1" },
                { skill: "Speed Sharpening", points: 2, type: 1, name: "Speed Sharpening Lv2" },
                { skill: "Speed Sharpening", points: 3, type: 1, name: "Speed Sharpening Lv3" },
            ]
        },
        {
            genre: "sg_ranged",
            skills: [
                { skill: "Blast Functionality", points: 1, type: 1, name: "Blast Functionality Lv1" },
                { skill: "Bow Charge Plus", points: 1, type: 1, name: "Bow Charge Plus Lv1" },
                { skill: "Normal Shots", points: 1, type: 1, name: "Normal Shots Lv1" },
                { skill: "Paralysis Functionality", points: 1, type: 1, name: "Paralysis Functionality Lv1" },
                { skill: "Piercing Shots", points: 1, type: 1, name: "Piercing Shots Lv1" },
                { skill: "Poison Functionality", points: 1, type: 1, name: "Poison Functionality Lv1" },
                { skill: "Sleep Functionality", points: 1, type: 1, name: "Sleep Functionality Lv1" },
                { skill: "Special Ammo Boost", points: 1, type: 1, name: "Special Ammo Boost Lv1" },
                { skill: "Special Ammo Boost", points: 2, type: 1, name: "Special Ammo Boost Lv2" },
                { skill: "Spread/Power Shots", points: 1, type: 1, name: "Spread/Power Shots Lv1" },
            ]
        },
  {
            genre: "sg_damage",
            skills: [
                { skill: "Affinity Sliding", points: 1, type: 1, name: "Affinity Sliding Lv1" },
                { skill: "Agitator", points: 1, type: 1, name: "Agitator Lv1" },
                { skill: "Agitator", points: 2, type: 1, name: "Agitator Lv2" },
                { skill: "Agitator", points: 3, type: 1, name: "Agitator Lv3" },
                { skill: "Agitator", points: 4, type: 1, name: "Agitator Lv4" },
                { skill: "Agitator", points: 5, type: 1, name: "Agitator Lv5" },
                { skill: "Airborne", points: 1, type: 1, name: "Airborne Lv1" },
                { skill: "Artillery", points: 1, type: 1, name: "Artillery Lv1" },
                { skill: "Artillery", points: 2, type: 1, name: "Artillery Lv2" },
                { skill: "Artillery", points: 3, type: 1, name: "Artillery Lv3" },
                { skill: "Attack Boost", points: 1, type: 1, name: "Attack Boost Lv1" },
                { skill: "Attack Boost", points: 2, type: 1, name: "Attack Boost Lv2" },
                { skill: "Attack Boost", points: 3, type: 1, name: "Attack Boost Lv3" },
                { skill: "Attack Boost", points: 4, type: 1, name: "Attack Boost Lv4" },
                { skill: "Attack Boost", points: 5, type: 1, name: "Attack Boost Lv5" },
                { skill: "Attack Boost", points: 6, type: 1, name: "Attack Boost Lv6" },
                { skill: "Attack Boost", points: 7, type: 1, name: "Attack Boost Lv7" },
                { skill: "Critical Boost", points: 1, type: 1, name: "Critical Boost Lv1" },
                { skill: "Critical Boost", points: 2, type: 1, name: "Critical Boost Lv2" },
                { skill: "Critical Boost", points: 3, type: 1, name: "Critical Boost Lv3" },
                { skill: "Critical Draw", points: 1, type: 1, name: "Critical Draw Lv1" },
                { skill: "Critical Draw", points: 2, type: 1, name: "Critical Draw Lv2" },
                { skill: "Critical Draw", points: 3, type: 1, name: "Critical Draw Lv3" },
                { skill: "Critical Eye", points: 1, type: 1, name: "Critical Eye Lv1" },
                { skill: "Critical Eye", points: 2, type: 1, name: "Critical Eye Lv2" },
                { skill: "Critical Eye", points: 3, type: 1, name: "Critical Eye Lv3" },
                { skill: "Critical Eye", points: 4, type: 1, name: "Critical Eye Lv4" },
                { skill: "Critical Eye", points: 5, type: 1, name: "Critical Eye Lv5" },
                { skill: "Critical Eye", points: 6, type: 1, name: "Critical Eye Lv6" },
                { skill: "Critical Eye", points: 7, type: 1, name: "Critical Eye Lv7" },
                { skill: "Fortify", points: 1, type: 1, name: "Fortify Lv1" },
                { skill: "Heroics", points: 1, type: 1, name: "Heroics Lv1" },
                { skill: "Heroics", points: 2, type: 1, name: "Heroics Lv2" },
                { skill: "Heroics", points: 3, type: 1, name: "Heroics Lv3" },
                { skill: "Heroics", points: 4, type: 1, name: "Heroics Lv4" },
                { skill: "Heroics", points: 5, type: 1, name: "Heroics Lv5" },
                { skill: "Latent Power", points: 1, type: 1, name: "Latent Power Lv1" },
                { skill: "Latent Power", points: 2, type: 1, name: "Latent Power Lv2" },
                { skill: "Latent Power", points: 3, type: 1, name: "Latent Power Lv3" },
                { skill: "Latent Power", points: 4, type: 1, name: "Latent Power Lv4" },
                { skill: "Latent Power", points: 5, type: 1, name: "Latent Power Lv5" },
                { skill: "Maximum Might", points: 1, type: 1, name: "Maximum Might Lv1" },
                { skill: "Maximum Might", points: 2, type: 1, name: "Maximum Might Lv2" },
                { skill: "Maximum Might", points: 3, type: 1, name: "Maximum Might Lv3" },
                { skill: "Non-elemental Boost", points: 1, type: 1, name: "Non-elemental Boost Lv1" },
                { skill: "Peak Performance", points: 1, type: 1, name: "Peak Performance Lv1" },
                { skill: "Peak Performance", points: 2, type: 1, name: "Peak Performance Lv2" },
                { skill: "Peak Performance", points: 3, type: 1, name: "Peak Performance Lv3" },
                { skill: "Resentment", points: 1, type: 1, name: "Resentment Lv1" },
                { skill: "Resentment", points: 2, type: 1, name: "Resentment Lv2" },
                { skill: "Resentment", points: 3, type: 1, name: "Resentment Lv3" },
                { skill: "Resentment", points: 4, type: 1, name: "Resentment Lv4" },
                { skill: "Resentment", points: 5, type: 1, name: "Resentment Lv5" },
                { skill: "Weakness Exploit", points: 1, type: 1, name: "Weakness Exploit Lv1" },
                { skill: "Weakness Exploit", points: 2, type: 1, name: "Weakness Exploit Lv2" },
                { skill: "Weakness Exploit", points: 3, type: 1, name: "Weakness Exploit Lv3" }
            ]
        },
        {
            genre: "sg_sets",
            skills: [
                { skill: "Anjanath Will", points: 2, type: 2, name: "Adrenaline" },
                { skill: "Anjanath Will", points: 4, type: 2, name: "Stamina Cap Up (Anjanath)" },
                { skill: "Diablos Mastery", points: 2, type: 2, name: "Bludgeoner" },
                { skill: "Diablos Mastery", points: 4, type: 2, name: "Non-elemental Boost" },
                { skill: "Kirin Favor", points: 3, type: 2, name: "Capture Master" },
                { skill: "Commission Guidance", points: 4, type: 2, name: "Carving Master" },
                { skill: "Rathalos Mastery", points: 2, type: 2, name: "Critical Element" },
                { skill: "Rathalos Mastery", points: 4, type: 2, name: "Mind\u2019s Eye/Ballistics (Rathalos)" },
                { skill: "Zorah Magdaros Mastery", points: 3, type: 2, name: "Critical Status" },
                { skill: "Legiana Favor", points: 2, type: 2, name: "Good Luck" },
                { skill: "Legiana Favor", points: 4, type: 2, name: "Bow Charge Plus" },
                { skill: "Guild Guidance", points: 4, type: 2, name: "Great Luck" },
                { skill: "Uragaan Protection", points: 3, type: 2, name: "Guard Up" },
                { skill: "Bazelgeuse Protection", points: 3, type: 2, name: "Guts" },
                { skill: "Nergigante Hunger", points: 3, type: 2, name: "Hasten Recovery" },
                { skill: "Teostra Technique", points: 3, type: 2, name: "Master\u2019s Touch (Teostra)" },
                { skill: "Lunastra Favor", points: 2, type: 2, name: "Stamina Cap Up (Lunastra)" },
                { skill: "Lunastra Favor", points: 4, type: 2, name: "Mind\u2019s Eye/Ballistics (Lunastra)" },
                { skill: "Kushala Daora Flight", points: 3, type: 2, name: "Nullify Wind Pressure" },
                { skill: "Pink Rathian Mastery", points: 3, type: 2, name: "Poison Duration Up" },
                { skill: "Odogaron Mastery", points: 2, type: 2, name: "Punishing Draw" },
                { skill: "Odogaron Mastery", points: 4, type: 2, name: "Protective Polish" },
                { skill: "Xeno\u2019jiiva Divinity", points: 3, type: 2, name: "Razor Sharp/Spare Shot" },
                { skill: "Val Hazak Vitality", points: 3, type: 2, name: "Super Recovery" },
                { skill: "Soul of the Dragoon", points: 2, type: 2, name: "Elemental Airborne" },
              { skill: "Soul of the Dragoon", points: 4, type: 2, name: "Master\u2019s Touch (Behemoth)" }
            ]
        },
        {
            genre: "sg_general",
            skills: [
                { skill: "LV1 Slot Skill", points: 1, type: 3, name: "LV1 Slot Skill Lv1" },
                { skill: "LV1 Slot Skill", points: 2, type: 3, name: "LV1 Slot Skill Lv2" },
                { skill: "LV1 Slot Skill", points: 3, type: 3, name: "LV1 Slot Skill Lv3" },
                { skill: "LV1 Slot Skill", points: 4, type: 3, name: "LV1 Slot Skill Lv4" },
                { skill: "LV1 Slot Skill", points: 5, type: 3, name: "LV1 Slot Skill Lv5" },
                { skill: "LV1 Slot Skill", points: 6, type: 3, name: "LV1 Slot Skill Lv6" },
                { skill: "LV1 Slot Skill", points: 7, type: 3, name: "LV1 Slot Skill Lv7" },
                { skill: "LV2 Slot Skill", points: 1, type: 3, name: "LV2 Slot Skill Lv1" },
                { skill: "LV2 Slot Skill", points: 2, type: 3, name: "LV2 Slot Skill Lv2" },
                { skill: "LV2 Slot Skill", points: 3, type: 3, name: "LV2 Slot Skill Lv3" },
                { skill: "LV2 Slot Skill", points: 4, type: 3, name: "LV2 Slot Skill Lv4" },
                { skill: "LV2 Slot Skill", points: 5, type: 3, name: "LV2 Slot Skill Lv5" },
                { skill: "LV2 Slot Skill", points: 6, type: 3, name: "LV2 Slot Skill Lv6" },
                { skill: "LV2 Slot Skill", points: 7, type: 3, name: "LV2 Slot Skill Lv7" },
                { skill: "LV3 Slot Skill", points: 1, type: 3, name: "LV3 Slot Skill Lv1" },
                { skill: "LV3 Slot Skill", points: 2, type: 3, name: "LV3 Slot Skill Lv2" },
                { skill: "LV3 Slot Skill", points: 3, type: 3, name: "LV3 Slot Skill Lv3" },
                { skill: "LV3 Slot Skill", points: 4, type: 3, name: "LV3 Slot Skill Lv4" },
                { skill: "LV3 Slot Skill", points: 5, type: 3, name: "LV3 Slot Skill Lv5" },
                { skill: "LV3 Slot Skill", points: 6, type: 3, name: "LV3 Slot Skill Lv6" },
                { skill: "LV3 Slot Skill", points: 7, type: 3, name: "LV3 Slot Skill Lv7" }
            ]
        }
    ]
